### PR TITLE
Add Reading Statistics to preview pane

### PR DESCRIPTION
**Pull request by blockloop**
Use [TextStatistics](https://github.com/cgiffard/TextStatistics.js) to provide the user with nice statistics that will help improve writing. It's possible to give more detail to these statistics by adding a way to see the ideal numbers.

Screenshot: https://www.dropbox.com/s/f11cphs8j4j62l9/Screenshot%202014-02-14%2017.41.04.png

### CODE REVIEW

**Comment by blockloop** [comment]
I also added node_modules to the gitignore, which is ideal. If you had them included for some reason, skip 5423bab.

**Comment by rhiokim** [comment]
It's look like interesting.

**Comment by p-j** [comment]
You usually want your `node_modules` folder checked in, see :
- [npm's FAQ about this](https://www.npmjs.org/doc/faq.html#Should-I-check-my-node_modules-folder-into-git)
- [Mikeal Rogers' post on this](http://www.futurealoof.com/posts/nodemodules-in-git.html)

**Comment by blockloop** [comment]
Fair enough. Thanks for the info. I'll be sure to pass it on. I separated the commits so this should still be merge-able without the node_modules removal. —

**Pull request closed without merging**
